# Generated by Django 5.0 on 2023-12-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_buy_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='status',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='category',
            field=models.CharField(choices=[('Plot', 'Plot'), ('Flat', 'Flat'), ('Farm House', 'Farm House')], max_length=15),
        ),
    ]
